import StarProgress from "./StarProgress";

export const googleReviews = [
  {
    "Customer Name": "John Doe",
    Date: "2025-04-20",
    Ratings: <StarProgress rating={1.25} />,
    Comments: "Excellent service and quick response!",
  },
  {
    "Customer Name": "Priya Sharma",
    Date: "2025-04-19",
    Ratings: <StarProgress rating={5} />,
    Comments: "Good experience, will recommend.",
  },
  {
    "Customer Name": "Ahmed Khan",
    Date: "2025-04-18",
    Ratings: <StarProgress rating={3.5} />,
    Comments: "Average service, room for improvement.",
  },
  {
    "Customer Name": "Maria Gonzalez",
    Date: "2025-04-17",
    Ratings: <StarProgress rating={4.75} />,
    Comments: "Outstanding support, very helpful!",
  },
  {
    "Customer Name": "Lee Min-ho",
    Date: "2025-04-16",
    Ratings: <StarProgress rating={3} />,
    Comments: "Smooth process and friendly staff.",
  },
  {
    "Customer Name": "Sarah Johnson",
    Date: "2025-04-15",
    Ratings: <StarProgress rating={2} />,
    Comments: "Service was delayed, not satisfied.",
  },
  {
    "Customer Name": "David Brown",
    Date: "2025-04-14",
    Ratings: <StarProgress rating={1.5} />,
    Comments: "Highly professional and efficient.",
  },
  {
    "Customer Name": "Chen Wei",
    Date: "2025-04-13",
    Ratings: <StarProgress rating={3.75} />,
    Comments: "Very responsive and polite staff.",
  },
  {
    "Customer Name": "Amara Singh",
    Date: "2025-04-12",
    Ratings: <StarProgress rating={2.75} />,
    Comments: "Okay service, expected a bit more.",
  },
  {
    "Customer Name": "Luca Bianchi",
    Date: "2025-04-11",
    Ratings: <StarProgress rating={4.75} />,
    Comments: "Perfect experience from start to finish!",
  },
  {
    "Customer Name": "John Doe",
    Date: "2025-04-20",
    Ratings: <StarProgress rating={1.25} />,
    Comments: "Excellent service and quick response!",
  },
  {
    "Customer Name": "Priya Sharma",
    Date: "2025-04-19",
    Ratings: <StarProgress rating={5} />,
    Comments: "Good experience, will recommend.",
  },
  {
    "Customer Name": "Ahmed Khan",
    Date: "2025-04-18",
    Ratings: <StarProgress rating={3.5} />,
    Comments: "Average service, room for improvement.",
  },
  {
    "Customer Name": "Maria Gonzalez",
    Date: "2025-04-17",
    Ratings: <StarProgress rating={4.75} />,
    Comments: "Outstanding support, very helpful!",
  },
  {
    "Customer Name": "Lee Min-ho",
    Date: "2025-04-16",
    Ratings: <StarProgress rating={3} />,
    Comments: "Smooth process and friendly staff.",
  },
  {
    "Customer Name": "Sarah Johnson",
    Date: "2025-04-15",
    Ratings: <StarProgress rating={2} />,
    Comments: "Service was delayed, not satisfied.",
  },
  {
    "Customer Name": "David Brown",
    Date: "2025-04-14",
    Ratings: <StarProgress rating={1.5} />,
    Comments: "Highly professional and efficient.",
  },

];
export const campaignData = [
  
    {
      "Campaign ID": "2",
      "Channel": "Google Ads",
      "Start Date": "2024-05-01",
      "End Date": "2024-05-31",
      "Budget": "$500",
      "Leads": 25,
      "CPL": "$20"
    },
    {
      "Campaign ID": "12",
      "Channel": "Facebook",
      "Start Date": "2024-05-05",
      "End Date": "2024-06-05",
      "Budget": "$600",
      "Leads": 30,
      "CPL": "$20"
    },
    {
      "Campaign ID": "3",
      "Channel": "LinkedIn",
      "Start Date": "2024-05-10",
      "End Date": "2024-06-10",
      "Budget": "$400",
      "Leads": 15,
      "CPL": "$26.67"
    }
  
  
]

export const leadData = [
  {
    leadId: "#700201",
    createdDate: "2025-07-30",
    leadType: "New Lead",
    name: "Arjun Mehta",
    age: 32,
    weight: "70kg",
    circle: "North Zone",
    bdName: "Ravi Kumar",
    comments: "Interested in wellness package",
    status: "Active",
    leadTransfer: "Not Transferred"
  },
  {
    leadId: "#700202",
    createdDate: "2025-07-29",
    leadType: "Follow Up 1",
    name: "Priya Sharma",
    age: 45,
    weight: "62kg",
    circle: "East Zone",
    bdName: "",
    comments: "Requested a call back next week",
    status: "Pending",
    leadTransfer: "Transferred to South Team"
  },
  {
    leadId: "#700203",
    createdDate: "2025-07-28",
    leadType: "DNP 1",
    name: "Rahul Verma",
    age: 29,
    weight: "80kg",
    circle: "South Zone",
    bdName: "",
    comments: "Did not pick up, will retry",
    status: "On Hold",
    leadTransfer: "Not Transferred"
  },
  {
    leadId: "#700204",
    createdDate: "2025-07-27",
    leadType: "DNP 2",
    name: "Kavita Nair",
    age: 39,
    weight: "68kg",
    circle: "West Zone",
    bdName: "Neha Iyer",
    comments: "Still unreachable",
    status: "Inactive",
    leadTransfer: "Transferred to Retry Queue"
  },
  {
    leadId: "#700205",
    createdDate: "2025-07-26",
    leadType: "DNP Exh",
    name: "Suresh Rathi",
    age: 50,
    weight: "75kg",
    circle: "Central Zone",
    bdName: "Amit Singh",
    comments: "Previously unreachable, now responsive",
    status: "Active",
    leadTransfer: "Not Transferred"
  },
  {
    leadId: "#700206",
    createdDate: "2025-07-25",
    leadType: "Hot Lead",
    name: "Divya Joshi",
    age: 34,
    weight: "60kg",
    circle: "North Zone",
    bdName: "Ravi Kumar",
    comments: "Ready to sign up this week",
    status: "Hot",
    leadTransfer: "Not Transferred"
  },
  {
    leadId: "#700207",
    createdDate: "2025-07-24",
    leadType: "Junk Lead",
    name: "Manoj Patil",
    age: 41,
    weight: "85kg",
    circle: "South Zone",
    bdName: "Vikram Das",
    comments: "Wrong contact information",
    status: "Discarded",
    leadTransfer: "Not Transferred"
  },
  {
    leadId: "#700208",
    createdDate: "2025-07-23",
    leadType: "Out of City",
    name: "Nikita Jain",
    age: 28,
    weight: "55kg",
    circle: "West Zone",
    bdName: "Neha Iyer",
    comments: "Not in service area",
    status: "Out of Scope",
    leadTransfer: "Not Applicable"
  },
  {
    leadId: "#700209",
    createdDate: "2025-07-22",
    leadType: "Not Interested",
    name: "Abhishek Tiwari",
    age: 37,
    weight: "72kg",
    circle: "Central Zone",
    bdName: "Amit Singh",
    comments: "Declined offer",
    status: "Closed",
    leadTransfer: "Not Transferred"
  }
];

export const LeadsTableData = [
 
    {
      name: "John Doe",
      "contactNumber": "+1-234-567-8901",
      "email": "john.doe@example.com",
      "source": "Website",
      "leadStatus": "New",
      "notes": "Interested in premium package",
      "assignedConsultant": "Jane Smith"
    },
    {
      "name": "Emily Johnson",
      "contactNumber": "+1-987-654-3210",
      "email": "emily.johnson@example.com",
      "source": "Referral",
      "leadStatus": "Follow-up",
      "notes": "Requested a callback next week",
      "assignedConsultant": "Mike Brown"
    },
    {
      "name": "Michael Scott",
      "contactNumber": "+1-555-123-4567",
      "email": "michael.scott@example.com",
      "source": "Campaign",
      "leadStatus": "Converted",
      "notes": "Converted to customer",
      "assignedConsultant": "Kelly Kapoor"
    },
    {
      name: "John Doe",
      "contactNumber": "+1-234-567-8901",
      "email": "john.doe@example.com",
      "source": "Website",
      "leadStatus": "Lost",
      "notes": "Interested in premium package",
      "assignedConsultant": "Jane Smith"
    },
    {
      "name": "Emily Johnson",
      "contactNumber": "+1-987-654-3210",
      "email": "emily.johnson@example.com",
      "source": "Referral",
      "leadStatus": "In Progress",
      "notes": "Requested a callback next week",
      "assignedConsultant": "Mike Brown"
    },
    {
      "name": "Michael Scott",
      "contactNumber": "+1-555-123-4567",
      "email": "michael.scott@example.com",
      "source": "Campaign",
      "leadStatus": "Closed",
      "notes": "Converted to customer",
      "assignedConsultant": "Kelly Kapoor"
    }
  
  
]

export const AppointmentsTableData =[
  {
    "patientName": "John Doe",
    "contactNumber": "+1234567890",
    "email": "johndoe@example.com",
    "appointmentDate": "2025-05-15",
    "consultant": "Dr. Jane Smith",
    "treatmentType": "Physical Therapy",
    "notes": " requires a follow-up."
  },
  {
    "patientName": "Emily Clark",
    "contactNumber": "+9876543210",
    "email": "emilyclark@example.com",
    "appointmentDate": "2025-05-18",
    "consultant": "Dr. Michael Johnson",
    "treatmentType": "Dental Checkup",
    "notes": "Routine checkup and cleaning."
  },
  {
    "patientName": "Mark Evans",
    "contactNumber": "+1122334455",
    "email": "markevans@example.com",
    "appointmentDate": "2025-05-20",
    "consultant": "Dr. Sarah Lee",
    "treatmentType": "Cardiology",
    "notes": "Review heart rate monitoring data."
  }
]


export const PatientsData = [
  {
    leadId: "#658957",
    name: "William",
    age: 35,
    gender: "Male",
    treatment: "Knee Replacement",
    consultationType: "In-person",
    operationTime: "10:00 AM",
    operationDate: "2025-08-10",
    city: "Chennai",
    surgeonName: "Dr. Arjun Rao",
    hospitalName: "Apollo Hospital",
    hospitalAddress: "123, Mount Road, Chennai",
    amountPaid: 120000,
    paymentMode: "Credit Card",
    medicalCoordinator: "Anjali Mehta",
    phoneNumber: "95839 37825",
    emailId: "gjfjkgj@gmail.com",
    location: "Chennai",
    status: "Active",
  },
  {
    leadId: "#658958",
    name: "Sophia",
    age: 29,
    gender: "Female",
    treatment: "LASIK Surgery",
    consultationType: "Online",
    operationTime: "02:30 PM",
    operationDate: "2025-08-15",
    city: "Mumbai",
    surgeonName: "Dr. Neha Kapoor",
    hospitalName: "Vision Plus Clinic",
    hospitalAddress: "45, Marine Drive, Mumbai",
    amountPaid: 40000,
    paymentMode: "UPI",
    medicalCoordinator: "Ravi Sharma",
    phoneNumber: "98765 43210",
    emailId: "sophia@gmail.com",
    location: "Mumbai",
    status: "Pending",
  }
];


export const AppointmentData = [
  {
    tokenNo: "TK1002",
    name: "Jane Smith",
    phoneNumber: "9876543210",
    date: "2025-04-29",
    slot: "11:00 AM - 12:00 PM",
    status: "completed",
  },
  {
    tokenNo: "TK1003",
    name: "Mike Johnson",
    phoneNumber: "5551234567",
    date: "2025-04-30",
    slot: "09:00 AM - 10:00 AM",
    status: "cancelled",
  }, {
    tokenNo: "TK1003",
    name: "John Doe",
    phoneNumber: "1234567890",
    date: "2025-04-28",
    slot: "10:00 AM - 11:00 AM",
    status: "reschedule",
  },
];

export const FinanceData = [
  {
    invoiceId: "INV-001",
    name: "Ajay Kumar",
    hospitalName: "City General Hospital",
    doctorName: "Dr. Meena Rao",
    paymentType: "Cash",
    totalBill: 5000,
    settledAmount: 4500,
    company: "MediCorp",
    profits: 500,
  },
  {
    invoiceId: "INV-002",
    name: "Sanjay Pillai",
    hospitalName: "Apollo Hospitals",
    doctorName: "Dr. Rakesh Nair",
    paymentType: "Insurance",
    totalBill: 12000,
    settledAmount: 11500,
    company: "HealthPlus",
    profits: 500,
  },
  {
    invoiceId: "INV-003",
    name: "Priya Das",
    hospitalName: "Sunrise Medical Center",
    doctorName: "Dr. Anita Verma",
    paymentType: "Online",
    totalBill: 8000,
    settledAmount: 8000,
    company: "MedX",
    profits: 0,
  },
  {
    invoiceId: "INV-004",
    name: "Rahul Varma",
    hospitalName: "Global Care Hospital",
    doctorName: "Dr. Vikram Desai",
    paymentType: "Card",
    totalBill: 10000,
    settledAmount: 9500,
    company: "HealNow",
    profits: 500,
  },
  {
    invoiceId: "INV-005",
    name: "Deepa Iyer",
    hospitalName: "Lifeline Hospitals",
    doctorName: "Dr. Karthik R",
    paymentType: "UPI",
    totalBill: 6500,
    settledAmount: 6000,
    company: "MediCorp",
    profits: 500,
  },
];

export const appointmentData = [
  { date: "10.04.2025", totalAppointments: 50, appreciationCompleted: 46, revenue: 5487 },
  { date: "10.04.2025", totalAppointments: 50, appreciationCompleted: 46, revenue: 5487 },
  { date: "10.04.2025", totalAppointments: 50, appreciationCompleted: 46, revenue: 5487 },
];

export const campaigntData = [
  {
    campaignId: "#658957",
    channel: "Instagram",
    startDate: "10.04.2025",
    endDate: "10.04.2025",
    budget: 7658,
    leads: 67,
    cpl: 7658,
    link: "#"
  },
];
export const InvoiceTableData =[
  {
    "patientName": "John Doe",
    "surgeryFee": 2500,
    "additionalServices":"Follow-up Consultation", 
   
    "discount": 200,
    "paymentMethod": "Credit Card",
    "invoiceNumber": "INV-2025-001"
  },
  {
    "patientName": "Emily Clark",
    "surgeryFee": 3200,
    "additionalServices":"Follow-up Consultation",

    "discount": 300,
    "paymentMethod": "Bank Transfer",
    "invoiceNumber": "INV-2025-002"
  },
  {
    "patientName": "Mark Evans",
    "surgeryFee": 1800,
    "additionalServices": "Follow-up Consultation",
    "discount": 150,
    "paymentMethod": "Cash",
    "invoiceNumber": "INV-2025-003"
  }
]


export const RoleData =[
  {
   
    "Name": "Alice Johnson",
    "Roles": "Admin",
    PhoneNumber: "+1-202-555-0123",
    "Email": "alice.johnson@example.com",
    "Status": "Active",
    "CreatedBy": "Super Admin"
  },
  {
    "Name": "Bob Smith",
    "Roles": "Viewer",
    PhoneNumber: "+1-202-555-0456",
    "Email": "bob.smith@example.com",
    "Status": "Inactive",
    "CreatedBy": "Super Admin"
  },
  {
 
    "Name": "Charlie Brown",
    "Roles": "Editor",
    PhoneNumber: "+1-202-555-0789",
    "Email": "charlie.brown@example.com",
    "Status": "Active",
    "CreatedBy": "Super Admin"
  }
]

export const hospitalData = [
  {
    hospitalName: "City General Hospital",
    status: "Active",
    city: "Chennai",
    address: "Padur, Chennai",
    specialization: "Cardiology",
    contact: "97523 98756",
    overdue: 2000,
  },
  {
    hospitalName: "City General Hospital",
    status: "Active",
    city: "Chennai",
    address: "Padur, Chennai",
    specialization: "Cardiology",
    contact: "97523 98756",
    overdue: 3000,
  },
  {
    hospitalName: "City General Hospital",
    status: "Active",
    city: "Chennai",
    address: "Padur, Chennai",
    specialization: "Cardiology",
    contact: "97523 98756",
    overdue: 4030,
  },
  {
    hospitalName: "City General Hospital",
    status: "Inactive",
    city: "Chennai",
    address: "Padur, Chennai",
    specialization: "Cardiology",
    contact: "97523 98756",
    overdue: 0,
  },
  {
    hospitalName: "City General Hospital",
    status: "Inactive",
    city: "Chennai",
    address: "Padur, Chennai",
    specialization: "Cardiology",
    contact: "97523 98756",
    overdue: 0,
  },
  {
    hospitalName: "City General Hospital",
    status: "Inactive",
    city: "Chennai",
    address: "Padur, Chennai",
    specialization: "Cardiology",
    contact: "97523 98756",
    overdue: 0,
  },
  {
    hospitalName: "City General Hospital",
    status: "Active",
    city: "Chennai",
    address: "Padur, Chennai",
    specialization: "Cardiology",
    contact: "97523 98756",
    overdue: 5000,
  },
  {
    hospitalName: "City General Hospital",
    status: "Inactive",
    city: "Chennai",
    address: "Padur, Chennai",
    specialization: "Cardiology",
    contact: "97523 98756",
    overdue: 9000,
  },
  {
    hospitalName: "City General Hospital",
    status: "Inactive",
    city: "Chennai",
    address: "Padur, Chennai",
    specialization: "Cardiology",
    contact: "97523 98756",
    overdue: 25000,
  },
  {
    hospitalName: "City General Hospital",
    status: "Inactive",
    city: "Chennai",
    address: "Padur, Chennai",
    specialization: "Cardiology",
    contact: "97523 98756",
    overdue: 18000,
  },
  {
    hospitalName: "City General Hospital",
    status: "Active",
    city: "Chennai",
    address: "Padur, Chennai",
    specialization: "Cardiology",
    contact: "97523 98756",
    overdue: 30000,
  },
  {
    hospitalName: "City General Hospital",
    status: "Active",
    city: "Chennai",
    address: "Padur, Chennai",
    specialization: "Cardiology",
    contact: "97523 98756",
    overdue: 15500,
  }
];


export const doctorData = [
  {
    doctorName: "Mr. Ajay",
    status: "Active",
    city: "Chennai",
    experience: 5,
    specialization: "Cardiology",
    contact: "97523 98756",
    pendingPayment: 200,
  },
  {
    doctorName: "Mr. Ajay",
    status: "Active",
    city: "Chennai",
    experience: 5,
    specialization: "Cardiology",
    contact: "97523 98756",
    pendingPayment: 200,
  },
  {
    doctorName: "Mr. Ajay",
    status: "Active",
    city: "Chennai",
    experience: 5,
    specialization: "Cardiology",
    contact: "97523 98756",
    pendingPayment: 200,
  },
  {
    doctorName: "Mr. Ajay",
    status: "Inactive",
    city: "Chennai",
    experience: 5,
    specialization: "Cardiology",
    contact: "97523 98756",
    pendingPayment: 200,
  },
  {
    doctorName: "Mr. Ajay",
    status: "Inactive",
    city: "Chennai",
    experience: 5,
    specialization: "Cardiology",
    contact: "97523 98756",
    pendingPayment: 200,
  },
  {
    doctorName: "Mr. Ajay",
    status: "Inactive",
    city: "Chennai",
    experience: 5,
    specialization: "Cardiology",
    contact: "97523 98756",
    pendingPayment: 200,
  },
  {
    doctorName: "Mr. Ajay",
    status: "Active",
    city: "Chennai",
    experience: 5,
    specialization: "Cardiology",
    contact: "97523 98756",
    pendingPayment: 200,
  },
  {
    doctorName: "Mr. Ajay",
    status: "Inactive",
    city: "Chennai",
    experience: 5,
    specialization: "Cardiology",
    contact: "97523 98756",
    pendingPayment: 200,
  },
  {
    doctorName: "Mr. Ajay",
    status: "Inactive",
    city: "Chennai",
    experience: 5,
    specialization: "Cardiology",
    contact: "97523 98756",
    pendingPayment: 200,
  },
  {
    doctorName: "Mr. Ajay",
    status: "Inactive",
    city: "Chennai",
    experience: 5,
    specialization: "Cardiology",
    contact: "97523 98756",
    pendingPayment: 200,
  },
  {
    doctorName: "Mr. Ajay",
    status: "Active",
    city: "Chennai",
    experience: 5,
    specialization: "Cardiology",
    contact: "97523 98756",
    pendingPayment: 200,
  },
];

export const employeeData = [
  {
    "Employee ID": "EMP001",
    "Name": "John Doe",
    "Role ": "Doctor",
    "Department ": "Cardiology",
    "In Patient": "Yes",
    "Status": "Active"
  },
  {
    "Employee ID": "EMP002",
    "Name": "Jane Smith",
    "Role ": "Nurse",
    "Department ": "Pediatrics",
    "In Patient": "No",
    "Status": "Inactive"
  },
]

export const AttendanceData = [
  {
    name: "William",
    attendance: {
      1: true,
      2: true,
      3: true,
      4: true,
      5: true,
      6: false,
      7: false,
      8: true,
      9: true,
      10: true,
      11: true,
      12: true,
      13: true,
      14: false,
      15: false,
      16: true,
      17: true,
      18: true,
      19: true,
      20: true,
      21: false,
      22: false,
      23: true,
      24: true,
      25: true,
      26: true,
      27: true,
      28: true,
      29: true,
      30: true,
    },
  },
  {
    name: "John",
    attendance: {
      1: true,
      2: true,
      3: false,
      4: false,
      5: true,
      6: true,
      7: true,
      8: false,
      9: true,
      10: false,
      11: true,
      12: true,
      13: true,
      14: true,
      15: true,
      16: false,
      17: true,
      18: true,
      19: false,
      20: true,
      21: true,
      22: false,
      23: true,
      24: false,
      25: true,
      26: true,
      27: true,
      28: true,
      29: true,
      30: true,
    },
  },
  {
    name: "Emma",
    attendance: {
      1: true,
      2: false,
      3: true,
      4: true,
      5: true,
      6: true,
      7: false,
      8: true,
      9: true,
      10: true,
      11: true,
      12: false,
      13: false,
      14: true,
      15: true,
      16: true,
      17: false,
      18: true,
      19: true,
      20: false,
      21: true,
      22: false,
      23: true,
      24: true,
      25: false,
      26: true,
      27: true,
      28: false,
      29: true,
      30: true,
    },
  },
  {
    name: "Olivia",
    attendance: {
      1: true,
      2: true,
      3: false,
      4: true,
      5: true,
      6: true,
      7: true,
      8: true,
      9: false,
      10: false,
      11: true,
      12: true,
      13: true,
      14: true,
      15: false,
      16: true,
      17: true,
      18: true,
      19: false,
      20: true,
      21: false,
      22: true,
      23: true,
      24: true,
      25: true,
      26: true,
      27: false,
      28: true,
      29: true,
      30: true,
    },
  },
  {
    name: "Liam",
    attendance: {
      1: false,
      2: true,
      3: true,
      4: false,
      5: true,
      6: false,
      7: true,
      8: false,
      9: true,
      10: true,
      11: true,
      12: false,
      13: true,
      14: true,
      15: true,
      16: true,
      17: false,
      18: false,
      19: true,
      20: true,
      21: true,
      22: true,
      23: true,
      24: false,
      25: true,
      26: true,
      27: true,
      28: true,
      29: false,
      30: true,
    },
  },
  {
    name: "Noah",
    attendance: {
      1: true,
      2: false,
      3: true,
      4: true,
      5: false,
      6: true,
      7: false,
      8: true,
      9: false,
      10: true,
      11: false,
      12: true,
      13: true,
      14: true,
      15: true,
      16: true,
      17: true,
      18: true,
      19: true,
      20: false,
      21: true,
      22: false,
      23: true,
      24: false,
      25: false,
      26: true,
      27: true,
      28: true,
      29: true,
      30: true,
    },
  },
  {
    name: "Ava",
    attendance: {
      1: true,
      2: true,
      3: true,
      4: false,
      5: false,
      6: true,
      7: true,
      8: true,
      9: false,
      10: true,
      11: true,
      12: true,
      13: false,
      14: true,
      15: true,
      16: true,
      17: true,
      18: true,
      19: false,
      20: true,
      21: true,
      22: false,
      23: true,
      24: true,
      25: false,
      26: false,
      27: true,
      28: true,
      29: false,
      30: true,
    },
  },
  {
    name: "Sophia",
    attendance: {
      1: false,
      2: false,
      3: true,
      4: true,
      5: true,
      6: true,
      7: true,
      8: true,
      9: true,
      10: true,
      11: true,
      12: true,
      13: false,
      14: false,
      15: false,
      16: true,
      17: true,
      18: true,
      19: true,
      20: true,
      21: true,
      22: true,
      23: false,
      24: false,
      25: true,
      26: true,
      27: true,
      28: false,
      29: false,
      30: true,
    },
  },
  {
    name: "James",
    attendance: {
      1: true,
      2: true,
      3: true,
      4: true,
      5: true,
      6: false,
      7: true,
      8: false,
      9: false,
      10: true,
      11: true,
      12: false,
      13: true,
      14: true,
      15: true,
      16: false,
      17: false,
      18: true,
      19: true,
      20: true,
      21: true,
      22: true,
      23: true,
      24: false,
      25: true,
      26: false,
      27: false,
      28: true,
      29: true,
      30: true,
    },
  },
  {
    name: "Mia",
    attendance: {
      1: true,
      2: false,
      3: false,
      4: false,
      5: true,
      6: true,
      7: false,
      8: true,
      9: true,
      10: true,
      11: true,
      12: true,
      13: true,
      14: true,
      15: true,
      16: true,
      17: true,
      18: true,
      19: true,
      20: false,
      21: false,
      22: true,
      23: true,
      24: false,
      25: true,
      26: true,
      27: true,
      28: false,
      29: true,
      30: true,
    },
  },
  {
    name: "Charlotte",
    attendance: {
      1: false,
      2: true,
      3: true,
      4: true,
      5: true,
      6: true,
      7: true,
      8: true,
      9: true,
      10: true,
      11: true,
      12: false,
      13: true,
      14: false,
      15: true,
      16: true,
      17: true,
      18: true,
      19: true,
      20: true,
      21: true,
      22: true,
      23: false,
      24: false,
      25: false,
      26: true,
      27: true,
      28: false,
      29: true,
      30: true,
    },
  },
  {
    name: "Elijah",
    attendance: {
      1: true,
      2: true,
      3: true,
      4: true,
      5: true,
      6: true,
      7: false,
      8: false,
      9: true,
      10: true,
      11: true,
      12: true,
      13: false,
      14: false,
      15: false,
      16: true,
      17: true,
      18: false,
      19: false,
      20: true,
      21: true,
      22: true,
      23: true,
      24: true,
      25: true,
      26: true,
      27: true,
      28: true,
      29: true,
      30: true,
    },
  },
  {
    name: "Isabella",
    attendance: {
      1: false,
      2: false,
      3: true,
      4: false,
      5: false,
      6: true,
      7: true,
      8: true,
      9: true,
      10: true,
      11: true,
      12: true,
      13: false,
      14: false,
      15: true,
      16: true,
      17: true,
      18: true,
      19: true,
      20: true,
      21: false,
      22: true,
      23: false,
      24: true,
      25: true,
      26: false,
      27: true,
      28: true,
      29: false,
      30: true,
    },
  },
  {
    name: "Lucas",
    attendance: {
      1: true,
      2: true,
      3: false,
      4: false,
      5: true,
      6: true,
      7: false,
      8: false,
      9: true,
      10: true,
      11: false,
      12: true,
      13: true,
      14: true,
      15: true,
      16: true,
      17: false,
      18: true,
      19: true,
      20: true,
      21: true,
      22: true,
      23: true,
      24: true,
      25: true,
      26: true,
      27: false,
      28: false,
      29: false,
      30: true,
    },
  },
  {
    name: "Harper",
    attendance: {
      1: true,
      2: true,
      3: true,
      4: true,
      5: true,
      6: false,
      7: true,
      8: true,
      9: false,
      10: true,
      11: false,
      12: true,
      13: true,
      14: true,
      15: false,
      16: true,
      17: true,
      18: true,
      19: true,
      20: true,
      21: true,
      22: false,
      23: true,
      24: true,
      25: true,
      26: true,
      27: true,
      28: true,
      29: true,
      30: false,
    },
  },
];

export const leaveData = [
  {
    "Employee Name": "John Doe",
    "Role ": "Doctor",
    "Leave Type ": "Sick Leave",
    "Dates": "2025-08-10 to 2025-08-12",
    " Reason": "Fever",
    "Status": "Approved"
  },
  {
    "Employee Name": "Jane Smith",
    "Role ": "Nurse",
    "Leave Type ": "Casual Leave",
    "Dates": "2025-08-15",
    " Reason": "Personal",
    "Status": "Pending"
  },
  {
    "Employee Name": "Michael Lee",
    "Role ": "Technician",
    "Leave Type ": "Annual Leave",
    "Dates": "2025-08-20 to 2025-08-25",
    " Reason": "Vacation",
    "Status": "Rejected"
  }
];

export const payrollData = [
  {
    "Employee Name": "John Doe",
    "Month": "August 2025",
    "Salary ": "80000",
    "Deductions ": "5000",
    "Overtime ": "2000",
    "Net Pay": "77000"
  },
  {
    "Employee Name": "Jane Smith",
    "Month": "August 2025",
    "Salary ": "80000",
    "Deductions ": "5000",
    "Overtime ": "2000",
    "Net Pay": "77000"
  },
  {
    "Employee Name": "Michael Lee",
    "Month": "August 2025",
    "Salary ": "80000",
    "Deductions ": "5000",
    "Overtime ": "2000",
    "Net Pay": "77000"
  }
];

export const profiledetailsData = {
  employeeId: "EMP001",
  name: "Name",
  designation: "Engineer",
  gender: "Female",
  dateOfBirth: "11.06.2000",
  mobileNumber: "00000 00000",
  emailId: "hdjhshhfhj@gmail.com",
  joiningDate: "11.06.2024",
  language: "English",
  reportingPerson: "Name",
  address: "Location",
};

export const tasksData = [
  {
    task: "Task",
    startDate: "01.08.2025",
    dueDate: "23.08.2025",
    assignedTo: "Priya",
    status: "Doing",
  },
  {
    task: "Task",
    startDate: "01.08.2025",
    dueDate: "23.08.2025",
    assignedTo: "Priya",
    status: "Completed",
  },
  {
    task: "Task",
    startDate: "01.08.2025",
    dueDate: "23.08.2025",
    assignedTo: "Priya",
    status: "Incomplete",
  },
  {
    task: "Task",
    startDate: "01.08.2025",
    dueDate: "23.08.2025",
    assignedTo: "Priya",
    status: "Doing",
  },
  {
    task: "Task",
    startDate: "01.08.2025",
    dueDate: "23.08.2025",
    assignedTo: "Priya",
    status: "Completed",
  },
  {
    task: "Task",
    startDate: "01.08.2025",
    dueDate: "23.08.2025",
    assignedTo: "Priya",
    status: "Completed",
  },
  {
    task: "Task",
    startDate: "01.08.2025",
    dueDate: "23.08.2025",
    assignedTo: "Priya",
    status: "Doing",
  },
  {
    task: "Task",
    startDate: "01.08.2025",
    dueDate: "23.08.2025",
    assignedTo: "Priya",
    status: "Completed",
  },
  {
    task: "Task",
    startDate: "01.08.2025",
    dueDate: "23.08.2025",
    assignedTo: "Priya",
    status: "Completed",
  },
  {
    task: "Task",
    startDate: "01.08.2025",
    dueDate: "23.08.2025",
    assignedTo: "Priya",
    status: "Completed",
  },
  {
    task: "Task",
    startDate: "01.08.2025",
    dueDate: "23.08.2025",
    assignedTo: "Priya",
    status: "Completed",
  },
];
